# This workflow will upload a Python Package using setup.py/twine when a release is created
# For more information see:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Create Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        # The PYPI_PASSWORD must be a pypi token with the "pypi-" prefix with sufficient permissions to upload this package
        # https://pypi.org/help/#apitoken
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 -m build
        twine upload dist/*
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install --no-install-recommends -y \
            latexmk \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            tex-gyre
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: install python dependencies
        run: python -m pip install -r docs/requirements.txt
      - name: build docs
        run: |
          cd docs
          make latexpdf
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docs/_build/latex/doppkit-esri-toolbox.pdf
  grab-dependencies:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: grab dependencies
        run: python -m pip download . --dest dist
      - name: zip directory
        run: |
          &"C:/Program Files/7-zip/7z.exe" a dependencies.zip ./dist/*
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dependencies.zip
